fix: link to contributing data from docs homepage
clearlydefined/clearlydefined pull request #188
Opened 2024-06-06 12:45 UTC by jmeridth

Currently the link 404s

2024-06-07 18:24 UTC, jmeridth commented
@nickvidal I've heard you might be the person to review this? 🙏 🙇

2024-06-07 18:27 UTC, nickvidal approved these changes
Thank you @jmeridth!

2024-06-07 18:27 UTC, merged

2024-06-08 21:25 UTC, saeedaziimi approved these changes

2024-06-08 23:18 UTC, saeedaziimi requested changes

2024-06-08 23:18 UTC, saeedaziimi commented on src/components/HomepageFeatures/index.js
> -    link: '/docs/get-involved/contribute-data',
میگوید پیکربندی اشتباه است